=== tyrcho/dota-items/dota.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with oXygen 6.2 -->
<!-- Last update 6.43b by Zorba on 2007/04/22 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="special" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="requires" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="mana" type="xs:int"/>
			<xs:attribute name="life" type="xs:int"/>
			<xs:attribute name="manaRegen" type="xs:int"/>
			<xs:attribute name="hitRegen" type="xs:int"/>
			<xs:attribute name="damage" type="xs:int"/>
			<xs:attribute name="armor" type="xs:int"/>
			<xs:attribute name="attackSpeed" type="xs:int"/>
			<xs:attribute name="moveSpeed" type="xs:int"/>
			<xs:attribute name="str" type="xs:int"/>
			<xs:attribute name="agi" type="xs:int"/>
			<xs:attribute name="int" type="xs:int"/>
			<xs:attribute name="cost" type="xs:int" use="required"/>
			<xs:attribute name="image"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="items">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="shop" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string"/>
		</xs:complexType>
		<xs:unique name="uniqueItemNames">
			<xs:selector xpath="shop/item"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:unique name="uniqueShopNames">
			<xs:selector xpath="shop"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:key name="itemKey">
			<xs:selector xpath="shop/item"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="requiresValue" refer="itemKey">
			<xs:selector xpath="shop/item/requires"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:element name="requires" type="xs:string"/>
	<xs:element name="shop">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="specialType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Activate"/>
			<xs:enumeration value="Aura"/>
			<xs:enumeration value="Effect"/>
			<xs:enumeration value="Orb"/>
			<xs:enumeration value="Info"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="special">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="specialType" use="required"/>
					<xs:attribute name="mana" type="xs:int"/>
					<xs:attribute name="cooldown" type="xs:int"/>
					<xs:attribute name="chance" type="xs:int"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tyrcho/dota-items/dota.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with Scite -->
<!-- Last update 6.52d by Zorba on 2008/07/03 -->
<!-- info in French at http://wikidota.org -->
<?xml-stylesheet type="text/xsl" href="dota.xsl"?>
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dota.xsd" version="6.52d">
	<shop name="Level 1 (Human) Recipes">
		<item name="Perseverance" image="OrbOfFire.gif" cost="0"  damage="10" hitRegen="5" manaRegen="125">
			<requires>Ring of Health</requires>
			<requires>Void Stone</requires>
		</item>
		<item name="Headdress of Rejuvenation" image="INV_Helmet_17.gif" cost="225" agi="2" int="2" str="2">
			<special type="Aura">+2 HP/Sec regen (500 AoE)</special>
			<requires>Ring of Regeneration</requires>
			<requires>Ironwood Branch</requires>
		</item>
		<item name="Netherezim Buckler" image="ThoriumArmor.gif" cost="200" armor="5" agi="2" str="2" int="2">
			<special type="Activate" mana="10" cooldown="25">+ 2 armor for nearby units for 25 sec (700 AoE)</special>
			<requires>Chain Mail</requires>
			<requires>Ironwood Branch</requires>
		</item>
		<item name="Basilius" image="RingVioletSpider.gif" cost="0" damage="6">
			<special type="Aura">Brilliance : +0.65 mana/sec to friendly units (900 AoE)</special>
			<special type="Aura">Devotion : +3 armor (900 AoE)</special>
			<requires>Sobi Mask</requires>
			<requires>Ring of Protection</requires>
		</item>
		<item name="Boots of Travel" image="Ability_Rogue_Sprint.gif" cost="2200" moveSpeed="85">
			<special type="Activate" mana="75" cooldown="60">Teleports to an allied unit or building</special>
			<requires>Boots of Speed</requires>
		</item>
		<item name="Power Treads(agi)" image="WirtsLeg.gif" cost="350" moveSpeed="65" attackSpeed="30" agi="10">
			<requires>Boots of Speed</requires>
			<requires>Gloves of Haste</requires>
			<requires>Boots of Elvenskin</requires>
		</item>
		<item name="Power Treads(int)" image="WirtsLeg.gif" cost="350" moveSpeed="65" attackSpeed="30" int="10">
			<requires>Boots of Speed</requires>
			<requires>Gloves of Haste</requires>
			<requires>Robe of the Magi</requires>
		</item>
		<item name="Power Treads(str)" image="WirtsLeg.gif" cost="350" moveSpeed="65" attackSpeed="30" str="10">
			<requires>Boots of Speed</requires>
			<requires>Gloves of Haste</requires>
			<requires>Belt of Giant Strength</requires>
		</item>
		<item name="Hands of Midas" image="GoldGloves.gif" cost="1400" attackSpeed="30">
			<special type="Activate" mana="25" cooldown="100">Transmutes a creep with level &lt; 5 to gold</special>
			<requires>Gloves of Haste</requires>
		</item>
		<item name="Oblivion Staff" image="INV_Mace_10.gif" cost="0" int="6" attackSpeed="10" damage="15" manaRegen="75">
			<requires>Quarter Staff</requires>
			<requires>Robe of the Magi</requires>
			<requires>Sobi Mask</requires>
		</item>
		<item name="Bracer" image="RunedBracers.gif" cost="175" agi="3" int="3" str="6">
			<requires>Circlet of Nobility</requires>
			<requires>Gauntlets of Strength</requires>
		</item>
		<item name="Wraith Band" image="Revenant.gif" cost="125" agi="6" int="3" str="3">
			<requires>Circlet of Nobility</requires>
			<requires>Slippers of Agility</requires>
		</item>
		<item name="Null Talisman" image="Talisman.gif" cost="175" agi="3" int="6" str="3">
			<requires>Circlet of Nobility</requires>
			<requires>Mantle of Intelligence</requires>
		</item>
	</shop>
	<shop name="Level 2 (Orc) Recipes">
		<item name="Yasha" image="INV_Sword_10.gif" cost="800" agi="16" moveSpeed="10" attackSpeed="10">
			<requires>Blade of Alacrity</requires>
			<requires>Boots of Elvenskin</requires>
		</item>
		<item name="Sange" image="JapaneseSword.gif" cost="800" str="16" damage="10">
			<special type="Orb" chance="10">Maim :+30 dmg, -35% attack and movement speed for 6 secondes</special>
			<requires>Ogre Axe</requires>
			<requires>Belt of Giant Strength</requires>
		</item>
		<item name="Cranium Basher" image="INV_Hammer_10.gif" cost="1460" damage="30" str="3">
			<special type="Effect">Bash : 15% Chance (10% for Ranged), 1.1 Second Stun</special>
			<special type="Info">+25 bonus dmg on Bash</special>
			<requires>Mithril Hammer</requires>
			<requires>Gauntlets of Strength</requires>
		</item>
		<item name="Blade Mail" image="INV_Chest_Plate06.gif" cost="500" armor="5" damage="15">
			<special type="Effect">Returns 20% dmg to melee attacker</special>
			<special type="Info">Blade Mails stack additively</special>
			<requires>Blades of Attack</requires>
			<requires>Chain Mail</requires>
		</item>
		<item name="Maelestrom" image="StormHammer.gif" cost="1300" agi="6" damage="25">
			<special type="Orb" chance="20">Chain ligthning dealing 150 dmg to 3 targets</special>
			<requires>Boots of Elvenskin</requires>
			<requires>Mithril Hammer</requires>
		</item>
		<item name="Diffusal Blade" image="INV_Sword_11.gif" cost="1550" agi="15" int="6">
			<special type="Activate" mana="0" cooldown="12">Purge (10 charges) for 4 seconds (600 range)</special>
			<special type="Orb">Feedback 18 Mana Burned per attack to heroes</special>
			<requires>Blade of Alacrity</requires>
			<requires>Robe of the Magi</requires>
		</item>
		<item name="Helm of the Dominator" image="INV_Helmet_13.gif" cost="0" damage="20" armor="5">
			<special type="Activate" mana="75" cooldown="300">Controls a creep for 20 minutes (700 range)</special>
			<special type="Orb" chance="100">15% Lifesteal</special>
			<requires>Helm of Iron Will</requires>
			<requires>Mask of Death</requires>
		</item>
		<item name="Mask of Madness" image="HelmOfValor.gif" cost="1050">
			<special type="Orb" chance="100">17% Lifesteal</special>
			<special type="Activate" mana="25" cooldown="30">Frenzy during 12 seconds : +75% attack speed, +15% run speed, dmg received +20%</special>
			<requires>Mask of Death</requires>
		</item>
		<item name="Eul's Scepter of Divinity" image="Staffofpurification.gif" cost="800" int="16" manaRegen="100" moveSpeed="20">
			<special type="Activate" cooldown="30" mana="75">Cyclone, 2.5 seconds duration (600 range)</special>
			<requires>Robe of the Magi</requires>
			<requires>Staff of Wizardry</requires>
			<requires>Void Stone</requires>
		</item>
		<item name="Soul Booster" image="PhilosophersStone.gif" cost="0" life="450" mana="400" manaRegen="10" hitRegen="1">
			<requires>Vitality Booster</requires>
			<requires>Energy Booster</requires>
			<requires>Point Booster</requires>
		</item>
		<item name="Mekansm" image="SpellShieldAmulet.gif" cost="900" int="5" agi="5" str="5" armor="5">
			<special type="Aura">+3 HP/sec to nearby units</special>
			<special type="Activate" cooldown="45" mana="150">Gives +2 armor and 250 hp AoE heal to friendly units</special>
			<requires>Headdress of Rejuvenation</requires>
			<requires>Netherezim Buckler</requires>
		</item>
	</shop>
	<shop name="Level 3 (Night Elf) Recipes">
		<item name="Sange and Yasha" image="Spell_Holy_BlessingOfStrength.gif" cost="800" agi="16"
			str="16" damage="15" moveSpeed="15" attackSpeed="15">
			<special type="Orb" chance="15">Maim :  -35% attack and movement speed for 6 seconds</special>
			<requires>Sange</requires>
			<requires>Yasha</requires>
		</item>
		<item name="Stygian Desolator" image="Ability_Gouge.gif" cost="1200" damage="60">
			<special type="Orb">Corruption :  -6 armor to enemy target, 5 sec duration</special>
			<requires>Mithril Hammer</requires>
			<requires>Mithril Hammer</requires>
		</item>
		<item name="Battle Fury" image="INV_ThrowingAxe_06.gif" cost="0" damage="65" manaRegen="150" hitRegen="6">
			<special type="Effect">gives splash attack : 35% dmg (225 AoE)</special>
			<requires>Claymore</requires>
			<requires>Broadsword</requires>
			<requires>Perseverance</requires>
		</item>
		<item name="Crystalys" image="ThoriumMelee.gif" cost="500" damage="35">
			<special type="Effect" chance="10">1.75x critical strike</special>
			<requires>Broadsword</requires>
			<requires>Blades of Attack</requires>
		</item>
		<item name="Black King Bar" image="RodOfNecromancy.gif" cost="1600" str="10" damage="18">
			<special type="Activate" cooldown="85">Avatar (Immue to most magic spells) for 9 sec</special>
			<requires>Ogre Axe</requires>
			<requires>Broadsword</requires>
		</item>
		<item name="Manta Style" image="INV_ThrowingAxe_02.gif" cost="1400" agi="23" int="6" life="250">
			<special type="Activate" cooldown="40" mana="165">Creates 2 illusions which deal 40% dmg and receive 300% dmg for 20 sec</special>
			<special type="Orb">Feedback : burns 36 mana</special>
			<requires>Vitality Booster</requires>
			<requires>Diffusal Blade</requires>
		</item>
		<!-- item name="Aegis of the Immortal" image="ArcaniteArmor.gif" cost="0">
			<special type="Effect"> Reincarnation (1 charge)</special>
			<special type="Info">Note: This item can only be obtained by killing Roshan.</special>
		</item -->
		<item name="Lothar's Edge" image="INV_Axe_16.gif" cost="650" agi="21" damage="21">
			<special type="Activate" mana="50" cooldown="17">Windwalk for 9 seconds (+20% run speed)</special>
			<special type="Info">Item can't be dropped</special>
			<requires>Blade of Alacrity</requires>
			<requires>Blade of Alacrity</requires>
			<requires>Claymore</requires>
		</item>
		<item name="Dagon" image="INV_Wand_06.gif" cost="1350" int="15" damage="9" agi="3" str="3">
			<special type="Activate" cooldown="40" mana="245">400 dmg ligthning (600 range)</special>
			<special type="Info">Upgrade with Dagon Recipe
				+100 dmg per upgrade (800 dmg max.)
				+20 mana cost per upgrade (325 mana max.)
				Each upgrade gives +2 intelligence</special>
			<requires>Staff of Wizardry</requires>
			<requires>Blades of Attack</requires>
		</item>
		<item name="Necronomicon" image="NecromancerAdept.gif" cost="1300" int="15" str="6">
			<special type="Activate" cooldown="90" mana="50">Raise dead, summons 1 Necronomicon Archer and a Necronomicon Warrior for 35 seconds.</special>
